//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Nikiforov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        public int ID { get; set; }
        public int SenderID { get; set; }
        public Nullable<int> TargetBookID { get; set; }
        public Nullable<int> TargetReviewID { get; set; }
        public string Reason { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Reviews Reviews { get; set; }
        public virtual Users Users { get; set; }
    }
}
